apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-depl
  namespace: hireverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: hireverse/payment-server
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: DATABASE_URL
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: STRIPE_API_KEY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: JWT_SECRET_KEY
          envFrom:
            - configMapRef:
                name: common-config

---
apiVersion: v1
kind: Service
metadata:
  name: payment-srv
  namespace: hireverse
spec:
  selector:
    app: payment
  ports:
    - name: express
      protocol: TCP
      port: 5005
      targetPort: 5005
    - name: grpc
      protocol: TCP
      port: 6005
      targetPort: 6005